language: node_js

node_js:
  - 12.13

branches:
  only:
    - master
    - develop

jobs:
  include:
    - state: "Build Client"
      name: "Build Client"
      before_script:
        - cd client
        - yarn
      script:
        - yarn build
    - state: "Build Server"
      name: "Build Server"
      before_script:
        - cd server
        - npm install
      script:
        - npm build

  jobs:
    include:
      - state: "Build Chat"
        name: "Build Chat"
        before_script:
          - cd chat-server
        script:
          - npm start
