version: "3"

services:
  mysql-server:
    image: mysql:5.7.28
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower_case_table_names=1
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=palda
      - MYSQL_USER=boost
      - MYSQL_PASSWORD=boost
      - MYSQL_ROOT_HOST=%

  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app:cached
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql-server

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  auction-server:
    build:
      context: ./auction-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
volumes:
  mysql:
