name: CI
on: [push]

defaults: 
  run: 
    working-directory: ./client # 실행되는 폴더 경로 저장

jobs:
  build:
    name: yarn script test (install, build, test)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2  # 브랜치 확인
        with:
          ref: 'develop'
      - name: use node version 12.13.0 # 노드 버전 설치
        uses: actions/setup-node@v2
        with:
          node-version: 12.13.0
          cache: yarn
          cache-dependency-path: client/package-lock.json

      - name: yarn install           # 설치
        run: yarn install

      - name: yarn test           # 테스트
        run: yarn test